---
- name: install docker
  hosts: all
  become: yes
  vars:
    - deploy_user: "docker-user"
    - key_file: "{{ '~/.ssh/id_rsa.pub' | expanduser }}"
  tasks:
    - apt:
        name: python3-pip
        state: present
    - pip:
        name: docker
    - user:
        name: "{{ deploy_user }}"
        group: docker
    - authorized_key:
        user: "{{ deploy_user }}"
        state: present
        key: "{{ lookup('file', key_file) }}"


  roles:
    - geerlingguy.docker
